### PR TITLE
Class Looper 2

### PR DESCRIPTION
**Pull request by s14774**
Plox

### CODE REVIEW

**Comment by ghost** [comment]
This branch has conflicts that must be resolved
to resolve conflicts before continuing.
Conflicting files
src/main/java/gitDemo/gitdemo/App.java

#zaorane

**Comment by jwolansk26** [comment]
**Blocking #1 resolved in 2a1f4b4** — supervisor MCP now lazily resolves actor, starts with empty string actor ID on empty DB, fails closed with proper messaging. `ensure-schema.ts` extracted and invoked before coordinator lookup. Tests: real stdio bootstrap flow, empty-DB startup, actor mode graceful degradation. ✓ All 664 tests pass.

**Comment by jwolansk26** [comment]
**Blocking #2 resolved in 2a1f4b4** — ?rate= now validated against canonical `RATE_OPTION_KINDS` enum on page, API, and MCP. Page degrades gracefully (no echo of invalid input), API returns clean 400, MCP enforces enum schema. Valid monthly/weekly/nightly rates work in all three paths. Tests: boundary conditions, invalid rates return 400, valid rates quote correctly. ✓

**Comment by jwolansk26** [comment]
**Blocking #3 resolved in 2a1f4b4** — docs/mcp-server.md now derives all 7 actor tools from `ACTOR_TOOL_NAMES` constant, documents all four catalog tools (search_listings, get_listing, check_availability, quote_price), removes stale "imagery all missing" claim. README.md:212 synced. ✓ Docs and code now consistent.

**Pull request closed without merging**
